Repository dabreadman/Node-Podman-OpenShift-CI-CD, pull requests merged in 2021-04, with the labels that each got.

#65 Fix rollback.yml
  .github/workflows/WORKFLOWS.md
  .github/workflows/rollback.yml
Labels: bug

#67 Update rollback.yml
  .github/workflows/WORKFLOWS.md
  .github/workflows/rollback.yml
Labels: bug, documentation

#61 Testing with Jest and Selenium's WebdriverJS!
  .gitignore
  covid-vue-app/package-lock.json
  covid-vue-app/package.json
  covid-vue-app/server.js
  covid-vue-app/test/TESTING.md
  covid-vue-app/test/frontend-test.js
  covid-vue-app/test/server.test.js
Labels: enhancement

#72 Major Rehaul of the application
  .github/workflows/cicd.yml
  covid-vue-app/.gitignore
  covid-vue-app/Dockerfile
  covid-vue-app/Dockerfiledev
  covid-vue-app/docker-compose.yml
  covid-vue-app/package-lock.json
  covid-vue-app/package.json
  covid-vue-app/public/favicon.ico
  covid-vue-app/public/index.html
  covid-vue-app/src/components/DataTable.vue
  covid-vue-app/src/components/StatsOverview.vue
  covid-vue-app/src/components/activeCasesOverview.vue
  covid-vue-app/src/components/closedCasesOverview.vue
  covid-vue-app/src/components/layouts/TheFooter.vue
  covid-vue-app/src/components/layouts/TheNavBar.vue
  covid-vue-app/src/pages/StatsPage.vue
  covid-vue-app/test/frontend-test.js
Labels: enhancement

#77 Test, pipeline fix, version tagging
  .github/workflows/WORKFLOWS.md
  .github/workflows/cicd.yml
  covid-vue-app/package.json
  covid-vue-app/server.js
  covid-vue-app/test/TESTING.md
  covid-vue-app/test/frontend-test.js
Labels: bug, enhancement

#82 Code restructure, add documentation
  .github/workflows/WORKFLOWS.md
  .github/workflows/cicd.yml
  README.md
  covid-vue-app/DEVELOP.md
  covid-vue-app/docker-compose.yml
  covid-vue-app/docker/.dockerignore
  covid-vue-app/docker/CONTAINER.md
  covid-vue-app/docker/Dockerfile
  covid-vue-app/docker/Dockerfiledev
  covid-vue-app/docker/docker-compose.yml
  covid-vue-app/package-lock.json
  covid-vue-app/server/container-package.json
  covid-vue-app/server/package-lock.json
  covid-vue-app/server/server.js
  covid-vue-app/test/server.test.js
Labels: documentation, enhancement, npm dependencies

#83 Added comments (documentation) for the Application code, added a proper footer.
  covid-vue-app/DEVELOP.md
  covid-vue-app/package-lock.json
  covid-vue-app/src/App.vue
  covid-vue-app/src/components/DataTable.vue
  covid-vue-app/src/components/HelloWorld.vue
  covid-vue-app/src/components/StatsOverview.vue
  covid-vue-app/src/components/Title.vue
  covid-vue-app/src/components/activeCasesOverview.vue
  covid-vue-app/src/components/closedCasesOverview.vue
  covid-vue-app/src/components/layouts/TheFooter.vue
  covid-vue-app/src/components/layouts/TheNavBar.vue
  covid-vue-app/src/main.js
  covid-vue-app/src/pages/StatsPage.vue
  covid-vue-app/src/pages/TheHomePage.vue
  covid-vue-app/src/routes.js
Labels: documentation
